### ISSUE TITLE
BlazorDynamicJavascriptRuntime does not exist on window

### ISSUE THREAD

**Issue by smimon** [jameschch/Blazor.DynamicJavascriptRuntime.Evaluator#1]
I was hoping to use your library, but I suspect something may have become broken with the 3.1 Blazor update - the message in the title is displayed when calling InvokeAsync. The MS team renamed the client-side object perhaps?

**Comment by jameschch** [comment]
The main reference for the project is Microsoft.JsInterop 3.1.0, which is not a beta release for Blazor so I expect it to be quite stable. Can I ask what versions of Blazor etc you have referenced? Are you getting any build errors?

It sounds like the script include has not been placed in the project where expected, which is more a nuget thing than blazor. It might help to remove and re-add the package and maybe clear the browser cache.

As a workaround you could download and manually add a reference to the required script (or paste it into your own):

[https://github.com/jameschch/Blazor.DynamicJavascriptRuntime.Evaluator/blob/master/Blazor.DynamicJavascriptRuntime.Evaluator/wwwroot/BlazorDynamicJavascriptRuntime.js](https://github.com/jameschch/Blazor.DynamicJavascriptRuntime.Evaluator/blob/master/Blazor.DynamicJavascriptRuntime.Evaluator/wwwroot/BlazorDynamicJavascriptRuntime.js)

**Comment by smimon** [comment]
Thank you for the response.

Apologies, in my initial post when I said "3.1 update" I in fact should have said the 3.2 preview update. I am referencing Blazor 3.2.0-preview1.20073, and version 1.0.10 of your library. There are no build errors.

I removed and re-added the NuGet package, cleared browser cache, but was still getting the error.

Including the required script manually as a workaround cleared up the error, thanks.

One more thing though, and forgive me if this is my lack of understanding - void expressions do not seem to execute at all at the Javascript side. In your examples, you simply show setting the context's expression to a void javascript expression, with no call to invoke afterwards - is this sufficient to get them to execute?

When I try something like
`(context as EvalContext).Expression = () => context.console.warn("testing 123");`
there is no effect - no error, but no console output. Adding an invoke statement afterwards doesn't make any difference.

Indeed, trying something I know should fail like
`(context as EvalContext).Expression = () => context.bananas.warn("testing 123");`
does not produce any error, either in C# or Javascript.

Is this as expected?

Cheers

**Comment by jameschch** [comment]
Expressions are evaluated either explicitly using an Invoke method, or implicitly when leaving the using block:

```
using (dynamic context = new EvalContext(JSRuntimeInstance))
{
    (context as EvalContext).Expression = () => context.bananas.warn("testing 123");
}
```

The 3.2 blazor beta removed support for standard2.0 which is a problem for most nuget packages out there. I'm surprised this effects the script include but at least there's a workaround.

**Comment by smimon** [comment]
Ok, that's great, many thanks for the support and the excellent library.
